databases:
  - name: render_demo_rails
    databaseName: render_demo_rails
    user: render_demo_rails_user

services:
  - type: web
    name: render_demo_rails
    env: ruby
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: render_demo_rails
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false